// ---------------------------------------------------------------------------
// Départements et communes, intégrés directement dans l'appli (pas d'appel
// réseau externe : l'aperçu artefact bloque les requêtes vers des API tierces,
// donc une liste embarquée est plus fiable qu'un chargement en direct).
// Liste complète des 101 départements français (96 métropole + 5 outre-mer).
// Chaque département a au moins sa préfecture ; plusieurs ont des communes
// alentours en plus. Dites-moi si vous voulez enrichir un département précis.
// ---------------------------------------------------------------------------
export const DEPARTEMENTS = [
  { code: "01", nom: "Ain", villes: ["Bourg-en-Bresse", "Oyonnax", "Bellegarde-sur-Valserine"] },
  { code: "02", nom: "Aisne", villes: ["Laon", "Saint-Quentin", "Soissons"] },
  { code: "03", nom: "Allier", villes: ["Moulins", "Montluçon", "Vichy"] },
  { code: "04", nom: "Alpes-de-Haute-Provence", villes: ["Digne-les-Bains", "Manosque"] },
  { code: "05", nom: "Hautes-Alpes", villes: ["Gap", "Briançon"] },
  { code: "06", nom: "Alpes-Maritimes", villes: ["Nice", "Cannes", "Antibes", "Grasse"] },
  { code: "07", nom: "Ardèche", villes: ["Privas", "Annonay", "Aubenas"] },
  { code: "08", nom: "Ardennes", villes: ["Charleville-Mézières", "Sedan"] },
  { code: "09", nom: "Ariège", villes: ["Foix", "Pamiers"] },
  { code: "10", nom: "Aube", villes: ["Troyes", "Romilly-sur-Seine"] },
  { code: "11", nom: "Aude", villes: ["Carcassonne", "Narbonne"] },
  { code: "12", nom: "Aveyron", villes: ["Rodez", "Millau"] },
  { code: "13", nom: "Bouches-du-Rhône", villes: ["Marseille", "Aix-en-Provence", "Aubagne", "Vitrolles"] },
  { code: "14", nom: "Calvados", villes: ["Caen", "Lisieux", "Bayeux"] },
  { code: "15", nom: "Cantal", villes: ["Aurillac", "Saint-Flour"] },
  { code: "16", nom: "Charente", villes: ["Angoulême", "Cognac"] },
  { code: "17", nom: "Charente-Maritime", villes: ["La Rochelle", "Rochefort", "Saintes"] },
  { code: "18", nom: "Cher", villes: ["Bourges", "Vierzon"] },
  { code: "19", nom: "Corrèze", villes: ["Tulle", "Brive-la-Gaillarde"] },
  { code: "2A", nom: "Corse-du-Sud", villes: ["Ajaccio", "Porto-Vecchio"] },
  { code: "2B", nom: "Haute-Corse", villes: ["Bastia", "Corte"] },
  { code: "21", nom: "Côte-d'Or", villes: ["Dijon", "Beaune", "Chenôve", "Talant"] },
  { code: "22", nom: "Côtes-d'Armor", villes: ["Saint-Brieuc", "Lannion", "Dinan"] },
  { code: "23", nom: "Creuse", villes: ["Guéret"] },
  { code: "24", nom: "Dordogne", villes: ["Périgueux", "Bergerac"] },
  { code: "25", nom: "Doubs", villes: ["Besançon", "Montbéliard"] },
  { code: "26", nom: "Drôme", villes: ["Valence", "Montélimar"] },
  { code: "27", nom: "Eure", villes: ["Évreux", "Vernon"] },
  { code: "28", nom: "Eure-et-Loir", villes: ["Chartres", "Dreux"] },
  { code: "29", nom: "Finistère", villes: ["Brest", "Quimper", "Concarneau", "Morlaix"] },
  { code: "30", nom: "Gard", villes: ["Nîmes", "Alès"] },
  { code: "31", nom: "Haute-Garonne", villes: ["Toulouse", "Colomiers", "Blagnac", "Muret"] },
  { code: "32", nom: "Gers", villes: ["Auch"] },
  { code: "33", nom: "Gironde", villes: ["Bordeaux", "Mérignac", "Pessac", "Talence"] },
  { code: "34", nom: "Hérault", villes: ["Montpellier", "Béziers", "Sète", "Castelnau-le-Lez"] },
  { code: "35", nom: "Ille-et-Vilaine", villes: ["Rennes", "Saint-Malo", "Fougères", "Vitré"] },
  { code: "36", nom: "Indre", villes: ["Châteauroux"] },
  { code: "37", nom: "Indre-et-Loire", villes: ["Tours", "Amboise"] },
  { code: "38", nom: "Isère", villes: ["Grenoble", "Vienne", "Bourgoin-Jallieu", "Voiron"] },
  { code: "39", nom: "Jura", villes: ["Lons-le-Saunier", "Dole"] },
  { code: "40", nom: "Landes", villes: ["Mont-de-Marsan", "Dax"] },
  { code: "41", nom: "Loir-et-Cher", villes: ["Blois", "Vendôme"] },
  { code: "42", nom: "Loire", villes: ["Saint-Étienne", "Roanne"] },
  { code: "43", nom: "Haute-Loire", villes: ["Le Puy-en-Velay"] },
  { code: "44", nom: "Loire-Atlantique", villes: ["Nantes", "Saint-Nazaire", "Rezé", "Orvault"] },
  { code: "45", nom: "Loiret", villes: ["Orléans", "Montargis"] },
  { code: "46", nom: "Lot", villes: ["Cahors"] },
  { code: "47", nom: "Lot-et-Garonne", villes: ["Agen", "Villeneuve-sur-Lot"] },
  { code: "48", nom: "Lozère", villes: ["Mende"] },
  { code: "49", nom: "Maine-et-Loire", villes: ["Angers", "Cholet", "Saumur"] },
  { code: "50", nom: "Manche", villes: ["Saint-Lô", "Cherbourg-en-Cotentin"] },
  { code: "51", nom: "Marne", villes: ["Châlons-en-Champagne", "Reims", "Épernay"] },
  { code: "52", nom: "Haute-Marne", villes: ["Chaumont", "Saint-Dizier"] },
  { code: "53", nom: "Mayenne", villes: ["Laval"] },
  { code: "54", nom: "Meurthe-et-Moselle", villes: ["Nancy", "Lunéville"] },
  { code: "55", nom: "Meuse", villes: ["Bar-le-Duc", "Verdun"] },
  { code: "56", nom: "Morbihan", villes: ["Vannes", "Lorient"] },
  { code: "57", nom: "Moselle", villes: ["Metz", "Thionville", "Sarreguemines", "Forbach"] },
  { code: "58", nom: "Nièvre", villes: ["Nevers"] },
  { code: "59", nom: "Nord", villes: ["Lille", "Roubaix", "Tourcoing", "Villeneuve-d'Ascq", "Dunkerque"] },
  { code: "60", nom: "Oise", villes: ["Beauvais", "Compiègne", "Creil"] },
  { code: "61", nom: "Orne", villes: ["Alençon"] },
  { code: "62", nom: "Pas-de-Calais", villes: ["Arras", "Calais", "Boulogne-sur-Mer", "Béthune"] },
  { code: "63", nom: "Puy-de-Dôme", villes: ["Clermont-Ferrand", "Riom"] },
  { code: "64", nom: "Pyrénées-Atlantiques", villes: ["Pau", "Bayonne", "Anglet"] },
  { code: "65", nom: "Hautes-Pyrénées", villes: ["Tarbes", "Lourdes"] },
  { code: "66", nom: "Pyrénées-Orientales", villes: ["Perpignan"] },
  { code: "67", nom: "Bas-Rhin", villes: ["Strasbourg", "Haguenau", "Schiltigheim", "Illkirch-Graffenstaden"] },
  { code: "68", nom: "Haut-Rhin", villes: ["Colmar", "Mulhouse"] },
  { code: "69", nom: "Rhône", villes: ["Lyon", "Villeurbanne", "Vénissieux", "Écully"] },
  { code: "70", nom: "Haute-Saône", villes: ["Vesoul"] },
  { code: "71", nom: "Saône-et-Loire", villes: ["Mâcon", "Chalon-sur-Saône"] },
  { code: "72", nom: "Sarthe", villes: ["Le Mans"] },
  { code: "73", nom: "Savoie", villes: ["Chambéry", "Aix-les-Bains"] },
  { code: "74", nom: "Haute-Savoie", villes: ["Annecy", "Annemasse", "Thonon-les-Bains"] },
  { code: "75", nom: "Paris", villes: ["Paris"] },
  { code: "76", nom: "Seine-Maritime", villes: ["Rouen", "Le Havre", "Dieppe"] },
  { code: "77", nom: "Seine-et-Marne", villes: ["Melun", "Meaux", "Fontainebleau"] },
  { code: "78", nom: "Yvelines", villes: ["Versailles", "Saint-Germain-en-Laye"] },
  { code: "79", nom: "Deux-Sèvres", villes: ["Niort"] },
  { code: "80", nom: "Somme", villes: ["Amiens", "Abbeville"] },
  { code: "81", nom: "Tarn", villes: ["Albi", "Castres"] },
  { code: "82", nom: "Tarn-et-Garonne", villes: ["Montauban"] },
  { code: "83", nom: "Var", villes: ["Toulon", "Fréjus", "Draguignan"] },
  { code: "84", nom: "Vaucluse", villes: ["Avignon", "Carpentras", "Orange", "Cavaillon", "Pertuis", "L'Isle-sur-la-Sorgue", "Sorgues", "Bollène", "Vaison-la-Romaine", "Apt", "Le Pontet", "Valréas", "Monteux", "Le Thor", "Pernes-les-Fontaines"] },
  { code: "85", nom: "Vendée", villes: ["La Roche-sur-Yon", "Les Sables-d'Olonne"] },
  { code: "86", nom: "Vienne", villes: ["Poitiers", "Châtellerault"] },
  { code: "87", nom: "Haute-Vienne", villes: ["Limoges"] },
  { code: "88", nom: "Vosges", villes: ["Épinal", "Saint-Dié-des-Vosges"] },
  { code: "89", nom: "Yonne", villes: ["Auxerre", "Sens"] },
  { code: "90", nom: "Territoire de Belfort", villes: ["Belfort"] },
  { code: "91", nom: "Essonne", villes: ["Évry-Courcouronnes", "Corbeil-Essonnes"] },
  { code: "92", nom: "Hauts-de-Seine", villes: ["Nanterre", "Boulogne-Billancourt", "Neuilly-sur-Seine"] },
  { code: "93", nom: "Seine-Saint-Denis", villes: ["Bobigny", "Saint-Denis", "Montreuil"] },
  { code: "94", nom: "Val-de-Marne", villes: ["Créteil", "Vitry-sur-Seine"] },
  { code: "95", nom: "Val-d'Oise", villes: ["Pontoise", "Argenteuil", "Cergy"] },
  { code: "971", nom: "Guadeloupe", villes: ["Basse-Terre", "Pointe-à-Pitre"] },
  { code: "972", nom: "Martinique", villes: ["Fort-de-France"] },
  { code: "973", nom: "Guyane", villes: ["Cayenne"] },
  { code: "974", nom: "La Réunion", villes: ["Saint-Denis", "Saint-Pierre"] },
  { code: "976", nom: "Mayotte", villes: ["Mamoudzou"] },
];
